name: 22S-PA02

on: [push]

env:
  EXE_NAME: PA02
  #INPUT_FILES:
  #OUTPUT_FILES: example-bruteforce.txt example-highvalue.txt example-custom.txt

jobs:
  build:
    name: Project_Building
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:

      - name: Checkout project repo from GitHub
        uses: actions/checkout@v1

      - name: Executable name Environment Variable
        run: |
          echo $EXE_NAME
          echo " "
          echo ${{runner.workspace}}
          echo " "
          echo $GITHUB_WORKSPACE
          echo " "
          g++ --version
          cmake --version

      - name: Create build environment
        run:  mkdir ${{runner.workspace}}/build

      - name: Configure the build
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build the project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build .

      - name: Run the project
        working-directory: ${{runner.workspace}}/build
        shell: bash
        #run: ./$EXE_NAME $INPUT_FILES
        run: ./$EXE_NAME

      #- name: Copy output files to artifact directory
      #  working-directory: ${{runner.workspace}}/build
      #  run: |
      #    mkdir artifacts
      #    for f in $OUTPUT_FILES
      #    do
      #    echo "  Copying $f"
      #    cp $f artifacts/
      #    done

      #- name: Upload output files to GitHub so they can be reviewed
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: project_output
      #    path: ${{runner.workspace}}/build/artifacts
